import { installerService } from "./database";
import type { Database } from "@/integrations/supabase/types";

type InstallerInsert = Database['public']['Tables']['installers']['Insert'];

// Helper function to get coordinates for German cities
const getCoordinates = (location: string): { latitude: number; longitude: number } => {
  const coordinates: Record<string, { latitude: number; longitude: number }> = {
    // Baden-Württemberg
    "Freiburg": { latitude: 47.9990, longitude: 7.8421 },
    "Stuttgart": { latitude: 48.7758, longitude: 9.1829 },
    "Karlsruhe": { latitude: 49.0069, longitude: 8.4037 },
    "Konstanz": { latitude: 47.6633, longitude: 9.1753 },
    
    // Bayern
    "München": { latitude: 48.1351, longitude: 11.5820 },
    "Augsburg": { latitude: 48.3705, longitude: 10.8978 },
    "Nürnberg": { latitude: 49.4521, longitude: 11.0767 },
    "Freising": { latitude: 48.4011, longitude: 11.7488 },
    
    // Berlin
    "Berlin": { latitude: 52.5200, longitude: 13.4050 },
    
    // Brandenburg
    "Potsdam": { latitude: 52.3989, longitude: 13.0667 },
    "Bad Belzig": { latitude: 52.1419, longitude: 12.5928 },
    
    // Bremen
    "Bremen": { latitude: 53.0793, longitude: 8.8017 },
    "Bremerhaven": { latitude: 53.5396, longitude: 8.5809 },
    
    // Hamburg
    "Hamburg": { latitude: 53.5511, longitude: 9.9937 },
    
    // Hessen
    "Frankfurt am Main": { latitude: 50.1109, longitude: 8.6821 },
    "Darmstadt": { latitude: 49.8728, longitude: 8.6512 },
    "Wiesbaden": { latitude: 50.0755, longitude: 8.2392 },
    
    // Mecklenburg-Vorpommern
    "Rostock": { latitude: 54.0924, longitude: 12.0991 },
    "Schwerin": { latitude: 53.6355, longitude: 11.4012 },
    "Greifswald": { latitude: 54.0968, longitude: 13.3879 },
    "Wismar": { latitude: 53.8931, longitude: 11.4624 },
    "Stralsund": { latitude: 54.3091, longitude: 13.0818 },
    "Güstrow": { latitude: 53.7972, longitude: 12.1774 },
    "Waren": { latitude: 53.5204, longitude: 12.6804 },
    
    // Niedersachsen
    "Aurich": { latitude: 53.4692, longitude: 7.4822 },
    "Oldenburg": { latitude: 53.1434, longitude: 8.2146 },
    "Hannover": { latitude: 52.3759, longitude: 9.7320 },
    "Osnabrück": { latitude: 52.2799, longitude: 8.0472 },
    "Braunschweig": { latitude: 52.2689, longitude: 10.5268 },
    "Emden": { latitude: 53.3675, longitude: 7.2068 },
    "Göttingen": { latitude: 51.5413, longitude: 9.9158 },
    "Meppen": { latitude: 52.6906, longitude: 7.2903 },
    "Hameln": { latitude: 52.1039, longitude: 9.3568 },
    
    // Nordrhein-Westfalen
    "Köln": { latitude: 50.9375, longitude: 6.9603 },
    "Düsseldorf": { latitude: 51.2277, longitude: 6.7735 },
    "Essen": { latitude: 51.4556, longitude: 7.0116 },
    "Münster": { latitude: 51.9607, longitude: 7.6261 },
    "Dortmund": { latitude: 51.5136, longitude: 7.4653 },
    "Krefeld": { latitude: 51.3388, longitude: 6.5853 },
    "Wuppertal": { latitude: 51.2562, longitude: 7.1508 }
  };
  
  // Extract city name from location string
  const cityName = location.split(',')[0].trim();
  return coordinates[cityName] || { latitude: 51.1657, longitude: 10.4515 }; // Default to Germany center
};

// Helper function to map energy type
const mapEnergyType = (energyType: string): "solar" | "wind" => {
  if (energyType === "both") return "solar"; // Default to solar for mixed companies
  return energyType as "solar" | "wind";
};

const comprehensiveInstallers: InstallerInsert[] = [
  // Baden-Württemberg (9 companies)
  {
    name: "ageff Solar Freiburg",
    company_name: "ageff GmbH",
    email: "info@ageff.de",
    phone: "+49 761 45892130",
    website: "www.ageff.de",
    address: "Schwarzwaldstraße 78, 79117 Freiburg",
    location: "Freiburg, Baden-Württemberg",
    energy_type: "solar",
    description: "Spezialisiert auf Solaranlagen, Batteriespeicher und Wallboxen. Mit 15 Jahren Erfahrung und umfassenden Zertifizierungen sind wir Ihr vertrauensvoller Partner für nachhaltige Energielösungen.",
    specialties: ["Solar", "Batteriespeicher", "Wallbox"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 15,
    rating: 4.8,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Freiburg", "Lörrach", "Offenburg", "Villingen-Schwenningen"],
    languages: ["Deutsch", "Englisch", "Französisch"],
    ...getCoordinates("Freiburg, Baden-Württemberg")
  },
  {
    name: "Solar Zentrum Baden-Württemberg",
    company_name: "Solar Zentrum BW GmbH",
    email: "kontakt@solar-zentrum.com",
    phone: "+49 711 78542100",
    website: "www.solar-zentrum.com",
    address: "Königstraße 10, 70173 Stuttgart",
    location: "Stuttgart, Baden-Württemberg",
    energy_type: "solar",
    description: "Führender Anbieter für Solaranlagen, Batteriespeicher und Smart Home Integration. 18 Jahre Erfahrung mit über 450 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Smart Home"],
    certifications: ["VDE", "TÜV", "ISO 9001", "Meisterbetrieb"],
    experience_years: 18,
    rating: 4.7,
    review_count: 156,
    verified: true,
    status: "active",
    service_areas: ["Stuttgart", "Karlsruhe", "Mannheim", "Heilbronn"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Stuttgart, Baden-Württemberg")
  },
  {
    name: "enerix Karlsruhe",
    company_name: "enerix Karlsruhe GmbH & Co. KG",
    email: "karlsruhe@enerix.de",
    phone: "+49 721 35468200",
    website: "www.enerix.de/standorte/enerix-karlsruhe",
    address: "Kaiserstraße 144, 76133 Karlsruhe",
    location: "Karlsruhe, Baden-Württemberg",
    energy_type: "solar",
    description: "Kompetenter Partner für Solaranlagen, Batteriespeicher und Wärmepumpen. 12 Jahre Erfahrung mit 320 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Wärmepumpen"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 12,
    rating: 4.6,
    review_count: 94,
    verified: true,
    status: "active",
    service_areas: ["Karlsruhe", "Pforzheim", "Baden-Baden", "Rastatt"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Karlsruhe, Baden-Württemberg")
  },
  {
    name: "Fuchs Solar Baden-Württemberg",
    company_name: "Fuchs Solar GmbH",
    email: "info@fuchs.solar",
    phone: "+49 7531 36289400",
    website: "www.fuchs.solar",
    address: "Bodanstraße 1, 78462 Konstanz",
    location: "Konstanz, Baden-Württemberg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Energieberatung am Bodensee. 14 Jahre Erfahrung mit regionalem Fokus.",
    specialties: ["Solar", "Batteriespeicher", "Energieberatung"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 14,
    rating: 4.5,
    review_count: 67,
    verified: true,
    status: "active",
    service_areas: ["Konstanz", "Singen", "Friedrichshafen", "Ravensburg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Konstanz, Baden-Württemberg")
  },
  {
    name: "PV Süd Freiburg",
    company_name: "PV Süd BW GmbH",
    email: "info@pv-sued-bw.de",
    phone: "+49 761 45789123",
    website: "www.pv-sued-bw.de",
    address: "Basler Straße 55, 79100 Freiburg",
    location: "Freiburg, Baden-Württemberg",
    energy_type: "solar",
    description: "Experte für Solaranlagen, Batteriespeicher und Gewerbe-PV. 16 Jahre Erfahrung mit 220 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 16,
    rating: 4.7,
    review_count: 78,
    verified: true,
    status: "active",
    service_areas: ["Freiburg", "Emmendingen", "Lahr", "Waldkirch"],
    languages: ["Deutsch"],
    ...getCoordinates("Freiburg, Baden-Württemberg")
  },
  {
    name: "Bau Solar Südwest",
    company_name: "Bau Solar Südwest GmbH",
    email: "info@bau-solar.de",
    phone: "+49 721 98765432",
    website: "www.bau-solar.de",
    address: "Durlacher Allee 100, 76137 Karlsruhe",
    location: "Karlsruhe, Baden-Württemberg",
    energy_type: "solar",
    description: "Vollservice-Anbieter für Solaranlagen, Batteriespeicher, Gewerbe-PV und Carports. 19 Jahre Erfahrung mit 380 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV", "Carports"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb", "ISO 9001"],
    experience_years: 19,
    rating: 4.8,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Karlsruhe", "Mannheim", "Heidelberg", "Pforzheim"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Karlsruhe, Baden-Württemberg")
  },
  {
    name: "Solartune Stuttgart",
    company_name: "Solartune GmbH Stuttgart",
    email: "info@solartune.de",
    phone: "+49 711 12345678",
    website: "www.solartune.de",
    address: "Königstraße 43, 70173 Stuttgart",
    location: "Stuttgart, Baden-Württemberg",
    energy_type: "solar",
    description: "Moderne Solaranlagen mit Batteriespeicher, Smart Home Integration und Wallbox. 8 Jahre Erfahrung mit 240 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Smart Home", "Wallbox"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 8,
    rating: 4.6,
    review_count: 85,
    verified: true,
    status: "active",
    service_areas: ["Stuttgart", "Ludwigsburg", "Esslingen", "Böblingen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Stuttgart, Baden-Württemberg")
  },
  {
    name: "Krasniqi Solar Freiburg",
    company_name: "Krasniqi Solar GmbH",
    email: "info@krasniqi-solar.de",
    phone: "+49 761 87654321",
    website: "www.krasniqi-solar.de",
    address: "Wiesentalstraße 15, 79115 Freiburg",
    location: "Freiburg, Baden-Württemberg",
    energy_type: "solar",
    description: "Familienbetrieb für Solaranlagen, Batteriespeicher und Energieberatung. 11 Jahre Erfahrung mit 160 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Energieberatung"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 11,
    rating: 4.5,
    review_count: 92,
    verified: true,
    status: "active",
    service_areas: ["Freiburg", "Titisee-Neustadt", "Breisach", "Müllheim"],
    languages: ["Deutsch", "Albanisch", "Englisch"],
    ...getCoordinates("Freiburg, Baden-Württemberg")
  },
  {
    name: "Photovoltaik BW Netzwerk",
    company_name: "PV-BW GmbH",
    email: "info@photovoltaik-bw.de",
    phone: "+49 711 98765432",
    website: "www.photovoltaik-bw.de",
    address: "Rotebühlstraße 121, 70178 Stuttgart",
    location: "Stuttgart, Baden-Württemberg",
    energy_type: "solar",
    description: "Netzwerk für Solaranlagen, Batteriespeicher und Großanlagen. 17 Jahre Erfahrung mit 420 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Großanlagen"],
    certifications: ["VDE", "TÜV", "DGS", "BAFA"],
    experience_years: 17,
    rating: 4.7,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Stuttgart", "Ulm", "Reutlingen", "Tübingen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Stuttgart, Baden-Württemberg")
  },

  // Bayern (9 companies)
  {
    name: "enerix München",
    company_name: "enerix München GmbH & Co. KG",
    email: "muenchen@enerix.de",
    phone: "+49 89 54321098",
    website: "www.enerix.de/standorte/enerix-muenchen",
    address: "Maximilianstraße 35, 80539 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Führender Anbieter für Solaranlagen, Batteriespeicher, Wallbox und Smart Home Integration. 14 Jahre Erfahrung mit 520 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Wallbox", "Smart Home"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.8,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["München", "Augsburg", "Freising", "Erding"],
    languages: ["Deutsch", "Englisch", "Italienisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Wegatech München",
    company_name: "Wegatech GmbH",
    email: "info@wegatech.de",
    phone: "+49 89 12345678",
    website: "www.wegatech.de/ratgeber/photovoltaik-muenchen",
    address: "Leopoldstraße 244, 80807 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Testsieger 2024 für Solaranlagen, Batteriespeicher und Komplettpakete. 12 Jahre Erfahrung mit 800 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Komplettpaket"],
    certifications: ["VDE", "TÜV", "ISO 9001", "BAFA"],
    experience_years: 12,
    rating: 4.9,
    review_count: 234,
    verified: true,
    status: "active",
    service_areas: ["München", "Augsburg", "Ingolstadt", "Rosenheim"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Isarsolar München",
    company_name: "Isarsolar GmbH",
    email: "info@isarsolar.de",
    phone: "+49 89 87654321",
    website: "www.isarsolar.de",
    address: "Tal 7, 80331 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Dachsanierung. 16 Jahre Erfahrung mit 340 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Dachsanierung"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb", "DGS"],
    experience_years: 16,
    rating: 4.7,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["München", "Starnberg", "Wolfratshausen", "Dachau"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Watt & Volt Elektro München",
    company_name: "Watt & Volt Elektro GmbH",
    email: "info@wattundvolt.com",
    phone: "+49 89 98765432",
    website: "www.wattundvolt.com",
    address: "Sendlinger Straße 8, 80331 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Elektroinstallateur mit Solaranlagen, Batteriespeicher und Smart Home Integration. 19 Jahre Erfahrung mit 280 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Elektroinstallation", "Smart Home"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 19,
    rating: 4.6,
    review_count: 98,
    verified: true,
    status: "active",
    service_areas: ["München", "Freising", "Landsberg", "Fürstenfeldbruck"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Solarwerke Bayern",
    company_name: "Solarwerke Bayern GmbH",
    email: "info@solarwerkebayern.de",
    phone: "+49 89 11223344",
    website: "www.solarwerkebayern.de",
    address: "Orleansstraße 46, 81667 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Bayernweiter Anbieter für Solaranlagen, Batteriespeicher und Gewerbe-PV. 15 Jahre Erfahrung mit 460 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 15,
    rating: 4.8,
    review_count: 189,
    verified: true,
    status: "active",
    service_areas: ["München", "Nürnberg", "Augsburg", "Regensburg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Solarland Bayern Augsburg",
    company_name: "Solarland Bayern GmbH",
    email: "info@solarlandbayern.de",
    phone: "+49 821 55667788",
    website: "www.solarlandbayern.de",
    address: "Fuggerstraße 26, 86150 Augsburg",
    location: "Augsburg, Bayern",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und E-Mobilität. 13 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "E-Mobilität"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 13,
    rating: 4.6,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Augsburg", "Günzburg", "Neu-Ulm", "Donauwörth"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Augsburg, Bayern")
  },
  {
    name: "Wegatech Nürnberg",
    company_name: "Wegatech Nürnberg GmbH",
    email: "nuernberg@wegatech.de",
    phone: "+49 911 98765432",
    website: "www.wegatech.de/ratgeber/photovoltaik-nuernberg",
    address: "Königstraße 93, 90402 Nürnberg",
    location: "Nürnberg, Bayern",
    energy_type: "solar",
    description: "Nürnberger Standort für Solaranlagen, Batteriespeicher und Komplettpakete. 11 Jahre Erfahrung mit 420 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Komplettpaket"],
    certifications: ["VDE", "TÜV", "ISO 9001"],
    experience_years: 11,
    rating: 4.7,
    review_count: 176,
    verified: true,
    status: "active",
    service_areas: ["Nürnberg", "Fürth", "Erlangen", "Bamberg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Nürnberg, Bayern")
  },
  {
    name: "Lumosolar Bayern",
    company_name: "Lumosolar GmbH",
    email: "info@lumosolar.de",
    phone: "+49 89 44556677",
    website: "www.lumosolar.de",
    address: "Theresienstraße 29, 80333 München",
    location: "München, Bayern",
    energy_type: "solar",
    description: "Innovative Solaranlagen mit Batteriespeicher und Solaranlagen-Verleih. 9 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Solaranlagen-Verleih"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 9,
    rating: 4.5,
    review_count: 87,
    verified: true,
    status: "active",
    service_areas: ["München", "Bad Tölz", "Miesbach", "Garmisch"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("München, Bayern")
  },
  {
    name: "Emondo Solar Freising",
    company_name: "Emondo GmbH",
    email: "info@emondo.de",
    phone: "+49 8161 12345678",
    website: "www.emondo.de",
    address: "Hauptstraße 42, 85354 Freising",
    location: "Freising, Bayern",
    energy_type: "solar",
    description: "Experte für Solaranlagen, Batteriespeicher und Elektroinstallation. 17 Jahre Erfahrung mit 350 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Elektroinstallation"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb", "ISO 9001"],
    experience_years: 17,
    rating: 4.8,
    review_count: 203,
    verified: true,
    status: "active",
    service_areas: ["Freising", "Erding", "Landshut", "Dingolfing"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Freising, Bayern")
  },

  // Berlin (10 companies)
  {
    name: "Solarwerkstatt Berlin",
    company_name: "Solarwerkstatt Berlin GmbH",
    email: "info@richtung-sonne.de",
    phone: "+49 30 12345678",
    website: "www.richtung-sonne.de",
    address: "Prenzlauer Allee 36, 10405 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Altbau-Sanierung. 30 Jahre Erfahrung mit 380 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Altbau-Sanierung"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 30,
    rating: 4.8,
    review_count: 245,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Potsdam", "Brandenburg an der Havel"],
    languages: ["Deutsch", "Englisch", "Türkisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "SolarX Berlin",
    company_name: "SolarX GmbH",
    email: "info@solarxgmbh.de",
    phone: "+49 30 87654321",
    website: "www.solarxgmbh.de",
    address: "Unter den Linden 21, 10117 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Premium-Anbieter für Solaranlagen, Batteriespeicher und Premium-Technik. 18 Jahre Erfahrung mit 450 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Premium-Technik"],
    certifications: ["VDE", "TÜV", "ISO 9001", "BAFA"],
    experience_years: 18,
    rating: 4.9,
    review_count: 198,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Potsdam", "Brandenburg", "Cottbus"],
    languages: ["Deutsch", "Englisch", "Polnisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Solar-pol Berlin",
    company_name: "Solar-pol GmbH",
    email: "info@solar-pol.de",
    phone: "+49 30 98765432",
    website: "www.solar-pol.de",
    address: "Warschauer Straße 70A, 10243 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Gewerbe-PV. 16 Jahre Erfahrung mit 320 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 16,
    rating: 4.7,
    review_count: 156,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Brandenburg", "Potsdam", "Oranienburg"],
    languages: ["Deutsch", "Polnisch", "Englisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Easy-Solar Berlin",
    company_name: "Easy-Solar GmbH",
    email: "info@easy-solar.de",
    phone: "+49 30 55443322",
    website: "www.easy-solar.de",
    address: "Friedrichstraße 95, 10117 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Einfache Solaranlagen, Batteriespeicher und Service. 14 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Service"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.6,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Brandenburg", "Potsdam"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "GFK Solar Berlin",
    company_name: "GFK Solar GmbH",
    email: "info@gfk-solar.de",
    phone: "+49 30 11998877",
    website: "www.gfk-solar.de",
    address: "Kurfürstendamm 56, 10707 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Energieberatung. 12 Jahre Erfahrung mit 220 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Energieberatung"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 12,
    rating: 4.5,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Potsdam", "Brandenburg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Elektro Schmidt Berlin",
    company_name: "Uwe Schmidt Elektrotechnik",
    email: "info@elektroschmidtberlin.de",
    phone: "+49 30 44332211",
    website: "www.elektroschmidtberlin.de",
    address: "Schönhauser Allee 142, 10435 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Elektroinstallateur mit Solaranlagen und Batteriespeicher. 25 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Elektroinstallation", "Batteriespeicher"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 25,
    rating: 4.7,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Potsdam"],
    languages: ["Deutsch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Solartechnik Lauckner Berlin",
    company_name: "Solartechnik Lauckner GmbH",
    email: "info@solartechnik-lauckner.de",
    phone: "+49 30 77889900",
    website: "www.solartechnik-lauckner.de",
    address: "Alexanderstraße 3, 10178 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und faire Preise. 17 Jahre Erfahrung mit 310 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Faire Preise"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 17,
    rating: 4.8,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Brandenburg", "Potsdam"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "SolarZentrum Berlin",
    company_name: "SolarZentrum Berlin e.V.",
    email: "info@solarzentrum-berlin.de",
    phone: "+49 30 90139-2070",
    website: "www.berlin.de/solarcity/solarzentrum",
    address: "Potsdamer Straße 188, 10783 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Beratungszentrum für Solaranlagen, Beratung und Förderung. 20 Jahre Erfahrung mit 150 Projekten jährlich.",
    specialties: ["Solar", "Beratung", "Förderung"],
    certifications: ["VDE", "BAFA", "DGS"],
    experience_years: 20,
    rating: 4.4,
    review_count: 78,
    verified: true,
    status: "active",
    service_areas: ["Berlin"],
    languages: ["Deutsch", "Englisch", "Türkisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Berliner Solarexperten",
    company_name: "Berliner Solarexperten GmbH",
    email: "kontakt@berliner-solarexperten.de",
    phone: "+49 30 22334455",
    website: "www.berliner-solarexperten.de",
    address: "Kastanienallee 77, 10435 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Experten für Solaranlagen, Batteriespeicher, Smart Home und Wallbox. 13 Jahre Erfahrung mit 260 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Smart Home", "Wallbox"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 13,
    rating: 4.6,
    review_count: 92,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Potsdam"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Berlin, Berlin")
  },
  {
    name: "Solar-Profis Berlin",
    company_name: "Solar-Profis Berlin GmbH & Co. KG",
    email: "info@solar-profis-berlin.de",
    phone: "+49 30 66778899",
    website: "www.solar-profis-berlin.de",
    address: "Torstraße 109, 10119 Berlin",
    location: "Berlin, Berlin",
    energy_type: "solar",
    description: "Profis für Solaranlagen, Batteriespeicher und Gewerbe-PV. 15 Jahre Erfahrung mit 390 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "DGS", "ISO 9001"],
    experience_years: 15,
    rating: 4.7,
    review_count: 178,
    verified: true,
    status: "active",
    service_areas: ["Berlin", "Brandenburg", "Potsdam"],
    languages: ["Deutsch", "Englisch", "Russisch"],
    ...getCoordinates("Berlin, Berlin")
  },

  // Brandenburg (4 companies)
  {
    name: "VOLT SOLAR Brandenburg",
    company_name: "VOLT SOLAR GmbH",
    email: "info@volt-solar.de",
    phone: "+49 331 12345678",
    website: "www.volt-solar.de",
    address: "Friedrich-Ebert-Straße 99, 14469 Potsdam",
    location: "Potsdam, Brandenburg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Agrar-PV. 16 Jahre Erfahrung mit 340 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Agrar-PV"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 16,
    rating: 4.8,
    review_count: 189,
    verified: true,
    status: "active",
    service_areas: ["Potsdam", "Brandenburg", "Cottbus", "Frankfurt/Oder"],
    languages: ["Deutsch", "Englisch", "Polnisch"],
    ...getCoordinates("Potsdam, Brandenburg")
  },
  {
    name: "enerix Brandenburg",
    company_name: "enerix Brandenburg GmbH & Co. KG",
    email: "brandenburg@enerix.de",
    phone: "+49 331 87654321",
    website: "www.enerix.de/standorte/enerix-brandenburg",
    address: "Brandenburger Straße 20, 14467 Potsdam",
    location: "Potsdam, Brandenburg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Landwirtschaft. 12 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Landwirtschaft"],
    certifications: ["VDE", "TÜV", "DGS", "BAFA"],
    experience_years: 12,
    rating: 4.7,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["Potsdam", "Brandenburg", "Werder", "Belzig"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Potsdam, Brandenburg")
  },
  {
    name: "SolarSun24 Potsdam",
    company_name: "SolarSun24 GmbH",
    email: "info@solaranlagenfirma.de",
    phone: "+49 331 55443322",
    website: "www.solaranlagenfirma.de/photovoltaik-potsdam",
    address: "Am Neuen Markt 9, 14467 Potsdam",
    location: "Potsdam, Brandenburg",
    energy_type: "solar",
    description: "Regionaler Service für Solaranlagen und Batteriespeicher. 14 Jahre Erfahrung mit 220 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Regionaler Service"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.6,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Potsdam", "Teltow", "Kleinmachnow", "Stahnsdorf"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Potsdam, Brandenburg")
  },
  {
    name: "RMW Energy Brandenburg",
    company_name: "RMW Energy GmbH",
    email: "info@rmw-energy.de",
    phone: "+49 33206 12345",
    website: "www.rmw-energy.de",
    address: "Dorfstraße 45, 14806 Bad Belzig",
    location: "Bad Belzig, Brandenburg",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, Batteriespeicher und Energieberatung. 18 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Batteriespeicher", "Energieberatung"],
    certifications: ["VDE", "TÜV", "BWE", "DGS"],
    experience_years: 18,
    rating: 4.8,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["Bad Belzig", "Brandenburg", "Potsdam", "Wittenberg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Bad Belzig, Brandenburg")
  },

  // Bremen (4 companies)
  {
    name: "Adler Solar Bremen",
    company_name: "Adler Solar GmbH Bremen",
    email: "info@adler-solar-bremen.de",
    phone: "+49 421 12345678",
    website: "www.adler-solar-bremen.de",
    address: "Vor dem Steintor 89, 28203 Bremen",
    location: "Bremen, Bremen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und maritime Anlagen. 16 Jahre Erfahrung mit 280 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Maritime Anlagen"],
    certifications: ["VDE", "TÜV", "energiekonsens", "Meisterbetrieb"],
    experience_years: 16,
    rating: 4.7,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Bremen", "Bremerhaven", "Delmenhorst", "Oldenburg"],
    languages: ["Deutsch", "Englisch", "Plattdeutsch"],
    ...getCoordinates("Bremen, Bremen")
  },
  {
    name: "Böttjer Energy Bremen",
    company_name: "Böttjer Energy GmbH",
    email: "info@boettjer-energy.de",
    phone: "+49 421 87654321",
    website: "www.boettjer-energy.de",
    address: "Westerstraße 114, 28199 Bremen",
    location: "Bremen, Bremen",
    energy_type: "solar",
    description: "Energiekonsens Partner für Solaranlagen und Batteriespeicher. 14 Jahre Erfahrung mit 240 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Energiekonsens Partner"],
    certifications: ["VDE", "TÜV", "energiekonsens", "BAFA"],
    experience_years: 14,
    rating: 4.6,
    review_count: 98,
    verified: true,
    status: "active",
    service_areas: ["Bremen", "Bremerhaven", "Bremen-Nord"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Bremen, Bremen")
  },
  {
    name: "Nordsee Solar Bremerhaven",
    company_name: "Nordsee Solar GmbH",
    email: "info@nordsee-solar.de",
    phone: "+49 471 55443322",
    website: "www.nordsee-solar.de",
    address: "Hafenstraße 220, 27568 Bremerhaven",
    location: "Bremerhaven, Bremen",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, maritime Projekte und Offshore. 19 Jahre Erfahrung mit 190 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Maritime Projekte", "Offshore"],
    certifications: ["VDE", "TÜV", "BWE", "Maritime Zertifizierung"],
    experience_years: 19,
    rating: 4.8,
    review_count: 156,
    verified: true,
    status: "active",
    service_areas: ["Bremerhaven", "Bremen", "Cuxhaven", "Wilhelmshaven"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Bremerhaven, Bremen")
  },
  {
    name: "Weser Solar Bremen",
    company_name: "Weser Solar e. K.",
    email: "info@weser-solar.de",
    phone: "+49 421 98765432",
    website: "www.weser-solar.de",
    address: "Schlachte 26, 28195 Bremen",
    location: "Bremen, Bremen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Denkmalschutz. 17 Jahre Erfahrung mit 160 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Denkmalschutz"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 17,
    rating: 4.5,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Bremen", "Lilienthal", "Achim", "Syke"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Bremen, Bremen")
  },

  // Hamburg (4 companies)
  {
    name: "Solaranlagenbau24 Hamburg",
    company_name: "Solaranlagenbau24 GmbH",
    email: "info@solaranlagenbau24.de",
    phone: "+49 40 12345678",
    website: "www.solaranlagenbau24.de",
    address: "Mönckebergstraße 11, 20095 Hamburg",
    location: "Hamburg, Hamburg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher in Norddeutschland. 15 Jahre Erfahrung mit 420 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Norddeutschland"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 15,
    rating: 4.9,
    review_count: 156,
    verified: true,
    status: "active",
    service_areas: ["Hamburg", "Lübeck", "Bremen", "Hannover"],
    languages: ["Deutsch", "Englisch", "Dänisch"],
    ...getCoordinates("Hamburg, Hamburg")
  },
  {
    name: "Hanseatic Solar Hamburg",
    company_name: "Hanseatic Solar GmbH",
    email: "info@hanseatic-solar.de",
    phone: "+49 40 87654321",
    website: "www.hanseatic-solar.de",
    address: "Speicherstadt Block R, 20457 Hamburg",
    location: "Hamburg, Hamburg",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, maritime Projekte. 22 Jahre Erfahrung mit 380 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Maritime Projekte"],
    certifications: ["VDE", "TÜV", "BWE", "Maritime Zertifizierung"],
    experience_years: 22,
    rating: 4.8,
    review_count: 234,
    verified: true,
    status: "active",
    service_areas: ["Hamburg", "Schleswig-Holstein", "Niedersachsen"],
    languages: ["Deutsch", "Englisch", "Dänisch"],
    ...getCoordinates("Hamburg, Hamburg")
  },
  {
    name: "Elbe Solar Hamburg",
    company_name: "Elbe Solar e.K.",
    email: "info@elbe-solar.de",
    phone: "+49 40 55443322",
    website: "www.elbe-solar.de",
    address: "Reeperbahn 154, 20359 Hamburg",
    location: "Hamburg, Hamburg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Stadtanlagen. 13 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Stadtanlagen"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 13,
    rating: 4.6,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Hamburg", "Harburg", "Bergedorf", "Wandsbek"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Hamburg, Hamburg")
  },
  {
    name: "Nord-Solar Hamburg",
    company_name: "Nord-Solar GmbH & Co. KG",
    email: "kontakt@nord-solar-hh.de",
    phone: "+49 40 98765432",
    website: "www.nord-solar-hh.de",
    address: "Jungfernstieg 47, 20354 Hamburg",
    location: "Hamburg, Hamburg",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Gewerbe-PV. 18 Jahre Erfahrung mit 350 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "DGS", "ISO 9001"],
    experience_years: 18,
    rating: 4.7,
    review_count: 178,
    verified: true,
    status: "active",
    service_areas: ["Hamburg", "Lüneburg", "Stade", "Pinneberg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Hamburg, Hamburg")
  },

  // Hessen (3 companies)
  {
    name: "Libertas Energy Frankfurt",
    company_name: "Libertas Energy GmbH",
    email: "info@libertas-energy.de",
    phone: "+49 69 12345678",
    website: "www.libertas-energy.de",
    address: "Zeil 106, 60313 Frankfurt am Main",
    location: "Frankfurt am Main, Hessen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher in der Finanzmetropole. 14 Jahre Erfahrung mit 380 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Finanzmetropole"],
    certifications: ["VDE", "TÜV", "DGS", "ISO 9001"],
    experience_years: 14,
    rating: 4.8,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["Frankfurt", "Offenbach", "Darmstadt", "Wiesbaden"],
    languages: ["Deutsch", "Englisch", "Französisch"],
    ...getCoordinates("Frankfurt am Main, Hessen")
  },
  {
    name: "Rhein-Main Solar Darmstadt",
    company_name: "Rhein-Main Solar GmbH",
    email: "info@rhein-main-solar.de",
    phone: "+49 6151 87654321",
    website: "www.rhein-main-solar.de",
    address: "Wilhelminenstraße 15, 64283 Darmstadt",
    location: "Darmstadt, Hessen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher in der Technologie-Region. 16 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Technologie-Region"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 16,
    rating: 4.7,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Darmstadt", "Frankfurt", "Mainz", "Aschaffenburg"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Darmstadt, Hessen")
  },
  {
    name: "Taunus Solar Wiesbaden",
    company_name: "Taunus Solar e.K.",
    email: "info@taunus-solar.de",
    phone: "+49 611 55443322",
    website: "www.taunus-solar.de",
    address: "Wilhelmstraße 32, 65183 Wiesbaden",
    location: "Wiesbaden, Hessen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher in Premium-Wohnlagen. 12 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Premium-Wohnlagen"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 12,
    rating: 4.6,
    review_count: 98,
    verified: true,
    status: "active",
    service_areas: ["Wiesbaden", "Mainz", "Bad Homburg", "Rüsselsheim"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Wiesbaden, Hessen")
  },

  // Mecklenburg-Vorpommern (8 companies)
  {
    name: "WIND-projekt Rostock",
    company_name: "WIND-projekt GmbH",
    email: "info@wind-projekt.de",
    phone: "+49 381 12345678",
    website: "www.wind-projekt.de",
    address: "Kröpeliner Straße 54, 18055 Rostock",
    location: "Rostock, Mecklenburg-Vorpommern",
    energy_type: "wind",
    description: "Spezialist für Wind- und Solarenergie, Offshore-Projekte und Großanlagen. 30 Jahre Erfahrung mit 45 Projekten jährlich.",
    specialties: ["Wind", "Solar", "Offshore-Projekte", "Großanlagen"],
    certifications: ["VDE", "TÜV", "BWE", "Offshore-Zertifizierung"],
    experience_years: 30,
    rating: 4.9,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Rostock", "Wismar", "Stralsund", "Greifswald"],
    languages: ["Deutsch", "Englisch", "Dänisch"],
    ...getCoordinates("Rostock, Mecklenburg-Vorpommern")
  },
  {
    name: "Nordex Energy Schwerin",
    company_name: "Nordex Energy GmbH Schwerin",
    email: "schwerin@nordex-energy.de",
    phone: "+49 385 87654321",
    website: "www.nordex-energy.de",
    address: "Mecklenburgstraße 45, 19053 Schwerin",
    location: "Schwerin, Mecklenburg-Vorpommern",
    energy_type: "wind",
    description: "Spezialist für Wind- und Solarenergie, Service und Wartung. 25 Jahre Erfahrung mit 120 Projekten jährlich.",
    specialties: ["Wind", "Solar", "Service", "Wartung"],
    certifications: ["VDE", "TÜV", "BWE", "ISO 9001"],
    experience_years: 25,
    rating: 4.8,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["Schwerin", "Ludwigslust", "Parchim", "Güstrow"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Schwerin, Mecklenburg-Vorpommern")
  },
  {
    name: "Ostwind Greifswald",
    company_name: "Ostwind Greifswald GmbH",
    email: "info@ostwind-greifswald.de",
    phone: "+49 3834 55443322",
    website: "www.ostwind-greifswald.de",
    address: "Lange Straße 14, 17489 Greifswald",
    location: "Greifswald, Mecklenburg-Vorpommern",
    energy_type: "wind",
    description: "Spezialist für Wind- und Solarenergie, Repowering und Küstenregion. 22 Jahre Erfahrung mit 85 Projekten jährlich.",
    specialties: ["Wind", "Solar", "Repowering", "Küstenregion"],
    certifications: ["VDE", "TÜV", "BWE", "Maritime Zertifizierung"],
    experience_years: 22,
    rating: 4.7,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Greifswald", "Stralsund", "Bergen", "Wolgast"],
    languages: ["Deutsch", "Englisch", "Polnisch"],
    ...getCoordinates("Greifswald, Mecklenburg-Vorpommern")
  },
  {
    name: "Implace Solar Wismar",
    company_name: "Implace Solar GmbH",
    email: "info@implace-solar.de",
    phone: "+49 3841 98765432",
    website: "www.implace-solar.de",
    address: "Am Markt 7, 23966 Wismar",
    location: "Wismar, Mecklenburg-Vorpommern",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und maritime Anwendungen. 14 Jahre Erfahrung mit 220 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Maritime Anwendungen"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.6,
    review_count: 98,
    verified: true,
    status: "active",
    service_areas: ["Wismar", "Schwerin", "Grevesmühlen", "Bad Doberan"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Wismar, Mecklenburg-Vorpommern")
  },
  {
    name: "Baltic Solar Rostock",
    company_name: "Baltic Solar GmbH",
    email: "info@baltic-solar-rostock.de",
    phone: "+49 381 44556677",
    website: "www.baltic-solar-rostock.de",
    address: "Warnemünder Straße 65, 18057 Rostock",
    location: "Rostock, Mecklenburg-Vorpommern",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Küstenklima. 16 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Küstenklima"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 16,
    rating: 4.5,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Rostock", "Warnemünde", "Bad Doberan", "Güstrow"],
    languages: ["Deutsch", "Englisch", "Dänisch"],
    ...getCoordinates("Rostock, Mecklenburg-Vorpommern")
  },
  {
    name: "Vorpommern Wind Stralsund",
    company_name: "Vorpommern Wind GmbH",
    email: "info@vorpommern-wind.de",
    phone: "+49 3831 22334455",
    website: "www.vorpommern-wind.de",
    address: "Ossenreyerstraße 52, 18439 Stralsund",
    location: "Stralsund, Mecklenburg-Vorpommern",
    energy_type: "wind",
    description: "Spezialist für Windenergie, Offshore und Repowering. 28 Jahre Erfahrung mit 35 Projekten jährlich.",
    specialties: ["Windenergie", "Offshore", "Repowering"],
    certifications: ["BWE", "TÜV", "Offshore-Zertifizierung"],
    experience_years: 28,
    rating: 4.8,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["Stralsund", "Bergen", "Grimmen", "Ribnitz-Damgarten"],
    languages: ["Deutsch", "Englisch", "Dänisch"],
    ...getCoordinates("Stralsund, Mecklenburg-Vorpommern")
  },
  {
    name: "Ostsee Energie Güstrow",
    company_name: "Ostsee Energie GmbH",
    email: "kontakt@ostsee-energie.de",
    phone: "+49 3843 11223344",
    website: "www.ostsee-energie.de",
    address: "Plauer Chaussee 7, 18273 Güstrow",
    location: "Güstrow, Mecklenburg-Vorpommern",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, Energieberatung und ländliche Projekte. 19 Jahre Erfahrung mit 95 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Energieberatung", "ländlich"],
    certifications: ["VDE", "TÜV", "BWE", "BAFA"],
    experience_years: 19,
    rating: 4.6,
    review_count: 78,
    verified: true,
    status: "active",
    service_areas: ["Güstrow", "Waren", "Neubrandenburg", "Demmin"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Güstrow, Mecklenburg-Vorpommern")
  },
  {
    name: "Müritz Solar Waren",
    company_name: "Müritz Solar e.K.",
    email: "info@mueritz-solar.de",
    phone: "+49 3991 55667788",
    website: "www.mueritz-solar.de",
    address: "Lange Straße 28, 17192 Waren (Müritz)",
    location: "Waren, Mecklenburg-Vorpommern",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Tourismus-Anlagen. 13 Jahre Erfahrung mit 140 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Tourismus-Anlagen"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 13,
    rating: 4.7,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Waren", "Neubrandenburg", "Röbel", "Malchin"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Waren, Mecklenburg-Vorpommern")
  },

  // Niedersachsen (9 companies)
  {
    name: "ENERCON Service Aurich",
    company_name: "ENERCON Service GmbH",
    email: "service@enercon.de",
    phone: "+49 4941 927-0",
    website: "www.enercon.de",
    address: "Dreekamp 5, 26605 Aurich",
    location: "Aurich, Niedersachsen",
    energy_type: "wind",
    description: "Weltmarktführer für Windenergie, Service und Wartung. 40 Jahre Erfahrung mit 1200 Projekten jährlich.",
    specialties: ["Windenergie", "Service", "Wartung", "Weltmarktführer"],
    certifications: ["BWE", "TÜV", "ISO 9001", "ISO 14001"],
    experience_years: 40,
    rating: 4.9,
    review_count: 567,
    verified: true,
    status: "active",
    service_areas: ["Aurich", "Emden", "Leer", "Wittmund", "International"],
    languages: ["Deutsch", "Englisch", "Spanisch", "Französisch"],
    ...getCoordinates("Aurich, Niedersachsen")
  },
  {
    name: "Volkswind Oldenburg",
    company_name: "Volkswind GmbH",
    email: "info@volkswind.de",
    phone: "+49 441 50595-0",
    website: "www.volkswind.de",
    address: "Bundesstraße 7, 26125 Oldenburg",
    location: "Oldenburg, Niedersachsen",
    energy_type: "wind",
    description: "Spezialist für Windenergie und Projektentwicklung international. 28 Jahre Erfahrung mit 85 Projekten jährlich.",
    specialties: ["Windenergie", "Projektentwicklung", "International"],
    certifications: ["BWE", "TÜV", "ISO 9001"],
    experience_years: 28,
    rating: 4.8,
    review_count: 234,
    verified: true,
    status: "active",
    service_areas: ["Oldenburg", "Bremen", "Wilhelmshaven", "European"],
    languages: ["Deutsch", "Englisch", "Französisch"],
    ...getCoordinates("Oldenburg, Niedersachsen")
  },
  {
    name: "Solaris Hannover",
    company_name: "Solaris Hannover GmbH",
    email: "info@solaris-hannover.de",
    phone: "+49 511 12345678",
    website: "www.solaris-hannover.de",
    address: "Georgstraße 50, 30159 Hannover",
    location: "Hannover, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Gewerbe-PV. 17 Jahre Erfahrung mit 360 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 17,
    rating: 4.7,
    review_count: 189,
    verified: true,
    status: "active",
    service_areas: ["Hannover", "Braunschweig", "Hildesheim", "Göttingen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Hannover, Niedersachsen")
  },
  {
    name: "Weser-Ems Solar Osnabrück",
    company_name: "Weser-Ems Solar GmbH",
    email: "info@weser-ems-solar.de",
    phone: "+49 541 87654321",
    website: "www.weser-ems-solar.de",
    address: "Große Straße 69, 49074 Osnabrück",
    location: "Osnabrück, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Landwirtschaft. 15 Jahre Erfahrung mit 280 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Landwirtschaft"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 15,
    rating: 4.6,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Osnabrück", "Münster", "Vechta", "Cloppenburg"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Osnabrück, Niedersachsen")
  },
  {
    name: "Norddeutsche Energietechnik",
    company_name: "Norddeutsche Energietechnik GmbH",
    email: "info@norddeutsche-energietechnik.de",
    phone: "+49 531 55443322",
    website: "www.norddeutsche-energietechnik.de",
    address: "Bohlweg 30, 38100 Braunschweig",
    location: "Braunschweig, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, Hybrid-Systeme und Forschung. 20 Jahre Erfahrung mit 150 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Hybrid-Systeme", "Forschung"],
    certifications: ["VDE", "TÜV", "BWE", "ISO 9001"],
    experience_years: 20,
    rating: 4.8,
    review_count: 167,
    verified: true,
    status: "active",
    service_areas: ["Braunschweig", "Wolfsburg", "Salzgitter", "Göttingen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Braunschweig, Niedersachsen")
  },
  {
    name: "Küsten Wind Emden",
    company_name: "Küsten Wind GmbH",
    email: "info@kuesten-wind.de",
    phone: "+49 4921 98765432",
    website: "www.kuesten-wind.de",
    address: "Hafenstraße 15, 26721 Emden",
    location: "Emden, Niedersachsen",
    energy_type: "wind",
    description: "Spezialist für Windenergie, Offshore und Küstenstandorte. 24 Jahre Erfahrung mit 65 Projekten jährlich.",
    specialties: ["Windenergie", "Offshore", "Küstenstandorte"],
    certifications: ["BWE", "TÜV", "Maritime Zertifizierung"],
    experience_years: 24,
    rating: 4.7,
    review_count: 198,
    verified: true,
    status: "active",
    service_areas: ["Emden", "Aurich", "Leer", "Wilhelmshaven"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Emden, Niedersachsen")
  },
  {
    name: "Harz Solar Göttingen",
    company_name: "Harz Solar e.K.",
    email: "kontakt@harz-solar.de",
    phone: "+49 551 44556677",
    website: "www.harz-solar.de",
    address: "Weender Straße 76, 37073 Göttingen",
    location: "Göttingen, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher in der Bergregion. 12 Jahre Erfahrung mit 160 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Bergregion"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 12,
    rating: 4.5,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Göttingen", "Northeim", "Einbeck", "Osterode"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Göttingen, Niedersachsen")
  },
  {
    name: "Emsland Energie Lingen",
    company_name: "Emsland Energie GmbH",
    email: "info@emsland-energie.de",
    phone: "+49 591 22334455",
    website: "www.emsland-energie.de",
    address: "Lingener Straße 40, 49716 Meppen",
    location: "Meppen, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solar- und Windenergie, Biogasanlagen und ländliche Projekte. 18 Jahre Erfahrung mit 140 Projekten jährlich.",
    specialties: ["Solar", "Wind", "Biogasanlagen", "ländlich"],
    certifications: ["VDE", "TÜV", "BWE", "BAFA"],
    experience_years: 18,
    rating: 4.6,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Meppen", "Lingen", "Papenburg", "Nordhorn"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Meppen, Niedersachsen")
  },
  {
    name: "Weserbergland Solar Hameln",
    company_name: "Weserbergland Solar GmbH",
    email: "info@weserbergland-solar.de",
    phone: "+49 5151 77889900",
    website: "www.weserbergland-solar.de",
    address: "Osterstraße 28, 31785 Hameln",
    location: "Hameln, Niedersachsen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Denkmalschutz. 14 Jahre Erfahrung mit 200 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Denkmalschutz"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.7,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["Hameln", "Hildesheim", "Holzminden", "Stadthagen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Hameln, Niedersachsen")
  },

  // Nordrhein-Westfalen (9 companies)
  {
    name: "Energiegewinner Köln",
    company_name: "Energiegewinner GmbH",
    email: "info@energiegewinner.de",
    phone: "+49 221 12345678",
    website: "www.energiegewinner.de",
    address: "Hahnenstraße 57, 50667 Köln",
    location: "Köln, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Führender Anbieter für Solaranlagen, Batteriespeicher und Energieberatung. 18 Jahre Erfahrung mit 500 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Energieberatung"],
    certifications: ["VDE", "TÜV", "DGS", "BAFA", "ISO 9001"],
    experience_years: 18,
    rating: 4.9,
    review_count: 289,
    verified: true,
    status: "active",
    service_areas: ["Köln", "Düsseldorf", "Bonn", "Aachen"],
    languages: ["Deutsch", "Englisch", "Französisch"],
    ...getCoordinates("Köln, Nordrhein-Westfalen")
  },
  {
    name: "energiva Düsseldorf",
    company_name: "energiva GmbH",
    email: "info@energiva.de",
    phone: "+49 211 87654321",
    website: "www.energiva.de",
    address: "Königsallee 92, 40212 Düsseldorf",
    location: "Düsseldorf, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Testsieger 2024 für Solaranlagen, Batteriespeicher. 15 Jahre Erfahrung mit 420 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Testsieger 2024"],
    certifications: ["VDE", "TÜV", "DGS", "Testsieger", "ISO 9001"],
    experience_years: 15,
    rating: 4.8,
    review_count: 234,
    verified: true,
    status: "active",
    service_areas: ["Düsseldorf", "Köln", "Essen", "Dortmund"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Düsseldorf, Nordrhein-Westfalen")
  },
  {
    name: "Elektro Ernst Köln",
    company_name: "Elektro Ernst GmbH",
    email: "info@elektroernst.de",
    phone: "+49 221 98765432",
    website: "www.elektroernst.de",
    address: "Ehrenstraße 32, 50672 Köln",
    location: "Köln, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Elektroinstallateur mit Solaranlagen und Batteriespeicher. 50 Jahre Erfahrung mit 350 Projekten jährlich.",
    specialties: ["Solar", "Elektroinstallation", "Batteriespeicher"],
    certifications: ["VDE", "TÜV", "Meisterbetrieb", "50 Jahre Erfahrung"],
    experience_years: 50,
    rating: 4.7,
    review_count: 456,
    verified: true,
    status: "active",
    service_areas: ["Köln", "Bonn", "Bergisch Gladbach", "Leverkusen"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Köln, Nordrhein-Westfalen")
  },
  {
    name: "Ruhr Solar Essen",
    company_name: "Ruhr Solar GmbH",
    email: "info@ruhr-solar.de",
    phone: "+49 201 55443322",
    website: "www.ruhr-solar.de",
    address: "Kennedyplatz 5, 45127 Essen",
    location: "Essen, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Industrieanlagen. 16 Jahre Erfahrung mit 340 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Industrieanlagen"],
    certifications: ["VDE", "TÜV", "DGS", "ISO 9001"],
    experience_years: 16,
    rating: 4.6,
    review_count: 178,
    verified: true,
    status: "active",
    service_areas: ["Essen", "Dortmund", "Duisburg", "Bochum"],
    languages: ["Deutsch", "Englisch", "Türkisch"],
    ...getCoordinates("Essen, Nordrhein-Westfalen")
  },
  {
    name: "Westfalen Energie Münster",
    company_name: "Westfalen Energie GmbH",
    email: "kontakt@westfalen-energie.de",
    phone: "+49 251 44556677",
    website: "www.westfalen-energie.de",
    address: "Prinzipalmarkt 8, 48143 Münster",
    location: "Münster, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Landwirtschaft. 14 Jahre Erfahrung mit 290 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Landwirtschaft"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 14,
    rating: 4.7,
    review_count: 145,
    verified: true,
    status: "active",
    service_areas: ["Münster", "Osnabrück", "Bielefeld", "Paderborn"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Münster, Nordrhein-Westfalen")
  },
  {
    name: "Phoenix Solar Dortmund",
    company_name: "Phoenix Solar Dortmund GmbH",
    email: "info@phoenix-solar-dortmund.de",
    phone: "+49 231 22334455",
    website: "www.phoenix-solar-dortmund.de",
    address: "Westenhellweg 102, 44137 Dortmund",
    location: "Dortmund, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Strukturwandel. 17 Jahre Erfahrung mit 380 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Strukturwandel"],
    certifications: ["VDE", "TÜV", "DGS", "ISO 9001"],
    experience_years: 17,
    rating: 4.8,
    review_count: 198,
    verified: true,
    status: "active",
    service_areas: ["Dortmund", "Bochum", "Hagen", "Unna"],
    languages: ["Deutsch", "Englisch", "Polnisch"],
    ...getCoordinates("Dortmund, Nordrhein-Westfalen")
  },
  {
    name: "Rheinland Solar Düsseldorf",
    company_name: "Rheinland Solar e.K.",
    email: "info@rheinland-solar.de",
    phone: "+49 211 77889900",
    website: "www.rheinland-solar.de",
    address: "Schadowstraße 86, 40212 Düsseldorf",
    location: "Düsseldorf, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Premium-Kunden. 13 Jahre Erfahrung mit 250 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Premium-Kunden"],
    certifications: ["VDE", "TÜV", "DGS"],
    experience_years: 13,
    rating: 4.6,
    review_count: 134,
    verified: true,
    status: "active",
    service_areas: ["Düsseldorf", "Neuss", "Krefeld", "Mönchengladbach"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Düsseldorf, Nordrhein-Westfalen")
  },
  {
    name: "Niederrhein Energie Krefeld",
    company_name: "Niederrhein Energie GmbH",
    email: "info@niederrhein-energie.de",
    phone: "+49 2151 11223344",
    website: "www.niederrhein-energie.de",
    address: "Hochstraße 45, 47798 Krefeld",
    location: "Krefeld, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Gewerbe-PV. 15 Jahre Erfahrung mit 190 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Gewerbe-PV"],
    certifications: ["VDE", "TÜV", "BAFA", "Meisterbetrieb"],
    experience_years: 15,
    rating: 4.5,
    review_count: 89,
    verified: true,
    status: "active",
    service_areas: ["Krefeld", "Mönchengladbach", "Viersen", "Kempen"],
    languages: ["Deutsch", "Englisch", "Niederländisch"],
    ...getCoordinates("Krefeld, Nordrhein-Westfalen")
  },
  {
    name: "Bergisches Solar Wuppertal",
    company_name: "Bergisches Solar GmbH",
    email: "kontakt@bergisches-solar.de",
    phone: "+49 202 99887766",
    website: "www.bergisches-solar.de",
    address: "Luisenstraße 15, 42103 Wuppertal",
    location: "Wuppertal, Nordrhein-Westfalen",
    energy_type: "solar",
    description: "Spezialist für Solaranlagen, Batteriespeicher und Hanglage. 12 Jahre Erfahrung mit 180 Projekten jährlich.",
    specialties: ["Solar", "Batteriespeicher", "Hanglage"],
    certifications: ["VDE", "TÜV", "DGS", "Meisterbetrieb"],
    experience_years: 12,
    rating: 4.7,
    review_count: 112,
    verified: true,
    status: "active",
    service_areas: ["Wuppertal", "Solingen", "Remscheid", "Velbert"],
    languages: ["Deutsch", "Englisch"],
    ...getCoordinates("Wuppertal, Nordrhein-Westfalen")
  }
];

export const seedComprehensiveDatabase = async () => {
  console.log(`Starting to seed database with ${comprehensiveInstallers.length} comprehensive installer data...`);
  
  try {
    for (const installer of comprehensiveInstallers) {
      await installerService.createInstaller(installer);
      console.log(`Added installer: ${installer.name}`);
    }
    console.log('Comprehensive database seeding completed successfully!');
  } catch (error) {
    console.error('Error seeding comprehensive database:', error);
  }
};

export { comprehensiveInstallers };
