// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnnggormxkqjysadfuoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impubmdnb3JteGtxanlzYWRmdW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjYxNDEsImV4cCI6MjA3MTcwMjE0MX0.86RUbLGTl2nfhLeQxVmNxw6SaB6gXjeNo9u1EAeeaYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});